import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.Container}>
      <Head>
        <title>Projetos Codelândia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.Main}></main>
    </div>
  );
};

export default Home;
