import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Logo from "../public/logo.svg";

const Home: NextPage = () => {
  return (
    <div className={styles.Container}>
      <Head>
        <title>Projetos Codelândia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.Header}>
        <Image src={Logo} alt="Codelândia" objectFit="fill" width={251} />

        <div className={styles.Menu}>
          <a
            href="https://github.com/luansilvae"
            target="_blank"
            className={styles.GithubButton}
            rel="noreferrer"
          >
            MEU GITHUB
          </a>
          <a href="#" className={styles.CommunityButton}>
            ENTRAR NA COMUNIDADE
          </a>
        </div>
      </header>

      <main className={styles.Main}></main>
    </div>
  );
};

export default Home;
